version: '3'

services:
  configuration-fetcher:
    image: gruz0/monitoring-configuration-fetcher:latest
    env_file:
      - .env
    volumes:
      - ./env:/public
    networks:
      - monitoring-composer

  configuration-service:
    image: gruz0/monitoring-configuration-service:latest
    env_file:
      - .env
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - monitoring-composer

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: "app"
      POSTGRES_DB: "app_development"
      POSTGRES_PASSWORD: "password"
    volumes:
      - .data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - monitoring-composer

networks:
  monitoring-composer:
