version: '3'

services:
  configuration-fetcher:
    image: gruz0/monitoring-configuration-fetcher:latest
    env_file:
      - .env
    volumes:
      - ./env:/public
    networks:
      - monitoring-composer

  configuration-service:
    image: gruz0/monitoring-configuration-service:latest
    env_file:
      - .env
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - monitoring-composer

  configuration-service-db:
    image: postgres:12
    environment:
      POSTGRES_USER: "app"
      POSTGRES_DB: "app_production"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./volumes/configuration-service-db-data:/var/lib/postgresql/data
      - ./volumes/postgres-enable-uuid-extension.sh:/docker-entrypoint-initdb.d/postgres-enable-uuid-extension.sh
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - monitoring-composer

networks:
  monitoring-composer:
